import { Download, Eye, FileBarChart, FileSpreadsheet, FileText, MoreHorizontal, Plus, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/layout/PageHeader";
import { StatusBadge } from "@/components/charts/StatusBadge";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { reports } from "@/data/reports";

const quickReports = [
  {
    title: "SAR Report",
    description: "Full Self-Assessment Report with annexures and evidence index.",
    icon: FileText
  },
  {
    title: "Criteria Summary Report",
    description: "Criterion-wise completion, metrics, and pending evidence.",
    icon: FileBarChart
  },
  {
    title: "Gap Analysis Report",
    description: "Prioritized gaps, owners, due dates, and suggested actions.",
    icon: FileSpreadsheet
  }
];

export function Reports() {
  return (
    <div className="space-y-8">
      <PageHeader
        title="Reports"
        subtitle="Generate NBA-ready reports and maintain a complete export history."
        actions={<GenerateReportDialog />}
      />

      <section className="grid grid-cols-3 gap-6">
        {quickReports.map((report) => (
          <Card key={report.title} className="p-6 hover:shadow-md">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary-soft text-primary">
              <report.icon className="h-6 w-6" />
            </div>
            <h3 className="mt-5 text-base font-semibold text-slate-950">{report.title}</h3>
            <p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{report.description}</p>
            <Button variant="outline" className="mt-5" onClick={() => toast.success(`${report.title} generation started`)}>
              Generate
            </Button>
          </Card>
        ))}
      </section>

      <Card>
        <CardHeader>
          <CardTitle>Reports History</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-hidden rounded-xl border border-slate-200">
            <table className="w-full min-w-[980px] text-left text-sm">
              <thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500">
                <tr>
                  {["Report Name", "Type", "Generated By", "Date", "Format", "Status", "Actions"].map((header) => (
                    <th key={header} className="px-4 py-3">
                      {header}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {reports.map((report) => (
                  <tr key={report.name} className="transition hover:bg-slate-50">
                    <td className="px-4 py-3 font-medium text-slate-900">{report.name}</td>
                    <td className="px-4 py-3">
                      <StatusBadge label={report.type} variant="info" />
                    </td>
                    <td className="px-4 py-3">
                      <span className="inline-flex items-center gap-2">
                        <Avatar className="h-7 w-7">
                          <AvatarFallback>{report.generatedBy.replace("Dr. ", "").slice(0, 2).toUpperCase()}</AvatarFallback>
                        </Avatar>
                        {report.generatedBy}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-slate-600">{report.date}</td>
                    <td className="px-4 py-3">
                      <StatusBadge label={report.format} variant="neutral" />
                    </td>
                    <td className="px-4 py-3">
                      <StatusBadge label={report.status} />
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-1">
                        <Button variant="ghost" size="icon">
                          <Download className="h-4 w-4" />
                        </Button>
                        <Button variant="ghost" size="icon">
                          <Eye className="h-4 w-4" />
                        </Button>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon">
                              <MoreHorizontal className="h-4 w-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            <DropdownMenuItem onClick={() => toast.success("Report regeneration queued")}>
                              <RefreshCw className="h-4 w-4" />
                              Re-generate
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function GenerateReportDialog() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button>
          <Plus className="h-4 w-4" />
          Generate New Report
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Generate New Report</DialogTitle>
          <DialogDescription>Select report type, format, and academic year for the export queue.</DialogDescription>
        </DialogHeader>
        <div className="mt-5 grid gap-4">
          <Input placeholder="Report name" defaultValue="NBA SAR Final Draft" />
          <Select defaultValue="sar">
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="sar">SAR Report</SelectItem>
              <SelectItem value="criteria">Criteria Summary</SelectItem>
              <SelectItem value="gap">Gap Analysis</SelectItem>
            </SelectContent>
          </Select>
          <Select defaultValue="pdf">
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="pdf">PDF</SelectItem>
              <SelectItem value="docx">DOCX</SelectItem>
              <SelectItem value="xlsx">XLSX</SelectItem>
            </SelectContent>
          </Select>
          <Button onClick={() => toast.success("Report generation started")}>Generate Report</Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
